version: '3.8'

services:
  # fastapi back
  web:
    build: .
    container_name: co2_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - emqx
    networks:
      - co2_network

  # broker emqx
  emqx:
    image: emqx:5.8
    container_name: co2_emqx
    restart: unless-stopped
    ports:
      - "1883:1883"   
      - "8083:8083"   
      - "18083:18083" #dashboard
    volumes:
      - ./emqx/data:/opt/emqx/data
    networks:
      - co2_network

networks:
  co2_network:
    driver: bridge
