services:
  - type: web
    name: co2-app
    runtime: docker
    region: oregon
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000
